basedir: /home/r933r/data/projects/nanopore/data/krebs_2020/

fast5_single_to_multi: /home/r933r/.conda/envs/gastrulation/bin/multi_to_single_fast5
tombo: /home/r933r/.conda/envs/gastrulation/bin/tombo
python: /home/r933r/.conda/envs/gastrulation/bin/python
reference: /home/r933r/data/projects/nanopore/data/krebs_2020/reference/dmel-all-chromosome-r6.29.fasta

samtools: /tbi/software/x86_64/samtools/samtools-1.5/el7/bin/samtools
nanopolish: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/opt/bin/nanopolish
minimap2: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/opt/bin/minimap2
megalodon: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/miniconda3/envs/megalodon/bin/megalodon
megalodon_calibration: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/miniconda3/envs/megalodon/lib/python3.7/site-packages/megalodon/model_data/dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg/megalodon_mod_calibration.npz
guppy_bc_server: /home/r933r/data/software/users/snajder/guppy/ont-guppy-cpu/bin/guppy_basecall_server
pycoQC: /home/r933r/.conda/envs/gastrulation/bin/pycoQC
Fast5_to_seq_summary: /home/r933r/.conda/envs/gastrulation/bin/Fast5_to_seq_summary

per_batch: 5
chroms: [2L,2R,3L,3R,4]
unique_samples: [invitro11_1, invitro12_1, invitro11_2, invitro12_2, footprinting]
#unique_samples: [invitro11_1, invitro12_1, footprinting]
mettypes: [cpg,gpc,dam]
basecall_id: '000'
