basedir: /home/r933r/data/projects/nanopore/data/krebs_2021_1/

fast5_single_to_multi: /home/r933r/.conda/envs/gastrulation/bin/multi_to_single_fast5
python: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/miniconda3/envs/nanopore/bin/python
reference: /home/r933r/data/projects/nanopore/data/krebs_2020/reference/dmel-all-chromosome-r6.29.fasta

samtools: /tbi/software/x86_64/samtools/samtools-1.5/el7/bin/samtools
nanopolish: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/opt/bin/nanopolish
minimap2: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/opt/bin/minimap2
pycoQC: /home/r933r/.conda/envs/gastrulation/bin/pycoQC
Fast5_to_seq_summary: /home/r933r/.conda/envs/gastrulation/bin/Fast5_to_seq_summary
guppy_dir: /home/r933r/data/software/users/snajder/guppy/ont-guppy

per_batch: 3
chroms: [2L,2R,3L,3R,4]
unique_samples: [pass]


mettypes: [cpg,gpc]
basecall_id: '000'
