threads: 32

basedir: /omics/groups/OE0540/internal/projects/chromothripsis_medulloblastoma/ont_pdx_2021/wgs_met_analysis/

python: /icgc/dkfzlsdf/analysis/B260/software/users/snajder/miniconda3/envs/nanopore/bin/python
reference: /omics/groups/OE0540/internal/users/snajder/reference/GRCH38/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
samtools: /tbi/software/x86_64/samtools/samtools-1.5/el7/bin/samtools
nanopolish: /omics/groups/OE0540/internal/software/users/snajder/nanopolish/nanopolish/nanopolish

minimap2: /omics/groups/OE0540/internal/software/users/snajder/minimap/minimap2/minimap2
pycoQC: /omics/groups/OE0540/internal/software/users/snajder/miniconda3/envs/nanopore/bin/pycoQC
Fast5_to_seq_summary: /home/r933r/.conda/envs/gastrulation/bin/Fast5_to_seq_summary

guppy_dir: /home/r933r/data/software/users/snajder/guppy/ont-guppy_5.0.11/

per_batch: 4
chroms: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,MT]
unique_samples: [Prim, BT]

scratch_dir: /gpu/data/OE0540/snajder/
gpu_params: '-q gpu-lowprio -gpu num=1:j_exclusive=yes:mode=exclusive_process:gmem=6G'

mettypes: [cpg]
basecall_id: '001'

